CREATE DATABASE geek_collaborators;
\c geek_collaborators;

CREATE TABLE fullstack_collaborators (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
language varchar,
contact int,
role varchar
);

CREATE TABLE fullstack (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
 owner varchar,
 owner_contact varchar
);
CREATE DATABASE geek_collaborators_test WITH TEMPLATE geek_collaborators;